In [1]:
import MySQLdb
import pandas as pd
import numpy as np
conn = MySQLdb.connect(host='54.65.19.253', port=3306, user='news', passwd='newsnews', db='news')

In [2]:
data = pd.read_sql('SELECT news.timestamp, title, class, gbp \
                   FROM news, gbp \
                   WHERE news.timestamp = gbp.timestamp AND \
                         news.timestamp >= 1483228800;', conn)

In [3]:
data.head()

,timestamp,title,class,gbp
0,1483286400,Briton killed while fighting against Isis in S...,uk-news,1.229379
1,1483372800,Fiji earthquake tsunami threat passes after 7....,world,1.225735
2,1483459200,Marine Le Pen cheers Ford move out of Mexico a...,world,1.229943
3,1483632000,"Southern rail, London Underground and BA staff...",uk-news,1.231003
4,1483545600,Southern rail: RMT agrees to direct talks with...,uk-news,1.241321

In [4]:
data.shape
data = data.loc[data['class'].isin(['uk-news', 'world',  'business','technology', 'money'])]

In [5]:
data = data.groupby('timestamp', as_index=False).agg(
    {'title':lambda name: ' '.join(name), 
     'gbp':lambda gbp:np.mean(gbp)})

In [6]:
data= data.sort_values(['timestamp'])

In [7]:
data

      timestamp                                              title       gbp
0    1483286400  Briton killed while fighting against Isis in S...  1.229379
1    1483372800  Fiji earthquake tsunami threat passes after 7....  1.225735
2    1483459200  Marine Le Pen cheers Ford move out of Mexico a...  1.229943
3    1483545600  Southern rail: RMT agrees to direct talks with...  1.241321
4    1483632000  Southern rail, London Underground and BA staff...  1.231003
5    1483718400  Harrods demonstrators block doorways during ti...  1.228700
6    1483804800  London Underground strike kicks off week of tu...  1.228800
7    1483891200  30-foot sinkhole in Philadelphia swallows car ...  1.216558
8    1483977600  Rapper sentenced to 23 years after raping and ...  1.216396
9    1484064000  BBC Scotland to launch new current affairs sho...  1.211712
10   1484150400  ILO warns of rise in social unrest and migrati...  1.221005
11   1484236800  Mexico must be ready to retaliate if Trump lev...  1.220213
12   1484323200  In Stoke Labour faces a Brexit byelection batt...  1.218075
13   1484409600  Fischer Energy joins UK retail market with 100...  1.217600
14   1484496000  Shakira and Joe Biden get Davos 2017 under way...  1.204620
15   1484582400  The long war of mini-Holland in Enfield Dame J...  1.238435
16   1484668800  Sir Ranulph Fiennes abandons bid to climb Acon...  1.230598
17   1484755200  WWII bomb discovery closes Waterloo and Westmi...  1.231872
18   1484841600  Two friends face jail over dare that ended in ...  1.233009
19   1484928000  Britain braced for blast of sub-zero temperatu...  1.237600
20   1485014400  Belfast police officer injured in drive-by sho...  1.237100
21   1485100800  Mayor of London calls for action after antisem...  1.248264
22   1485187200  Trident misfire spotlights the danger of fat f...  1.253408
23   1485273600  Record low inflation growth reflects the bizar...  1.262077
24   1485360000  Man, 25, charged with murder after fatal stabb...  1.258051
25   1485446400  AI watchdog needed to regulate automated decis...  1.253092
26   1485532800  Princes William and Harry plan statue of their...  1.255150
27   1485619200  French Socialists choose leftwing rebel Benoît...  1.254800
28   1485705600  Prince Charles happy to meet Trump to discuss ...  1.247823
29   1485792000  Philippines police paid to kill alleged drug o...  1.258387
..          ...                                                ...       ...
121  1493740800  Conservatives may push for fresh Commons vote ...  1.291403
122  1493827200  Photographer held after taking pictures of Hov...  1.291714
123  1493913600  Three men charged with murder over death of Gu...  1.294835
124  1494000000  Paisley and McGuinness: the movie. But is it a...  1.298063
125  1494086400  Two bodies found in search off Scottish coast ...  1.298103
126  1494172800  Pregnant British woman killed in traffic accid...  1.293949
127  1494259200  Standard Life and Aberdeen merger likely to me...  1.293745
128  1494345600  UN must reform to defend enlightenment values,...  1.293740
129  1494432000  Hundreds of knives seized in 18 months at UK s...  1.288526
130  1494518400  Time to test the track record of privatisation...  1.287979
131  1494604800  Emmanuel Macron races to train would-be MPs Ma...  1.288678
132  1494691200  Connecticut police obtain video appearing to s...  1.288703
133  1494777600  The victims of Ian Brady and Myra Hindley Gove...  1.291701
134  1494864000  Ex-BHS owner Dominic Chappell could be pursued...  1.290953
135  1494950400  Required reading for a refugees minister Briti...  1.294385
136  1495036800  Cineworld bosses to meet union over living wag...  1.300799
137  1495123200  Wales Coast Path is a fine legacy of Rhodri Mo...  1.301567
138  1495209600  Did Dutch hordes kill off the early Britons wh...  1.303280
139  1495296000  Diamond ring bought for £10 at car boot sale m...  1.303385
140  1495382400  UN panel releases draft treaty banning possess...  1.300583
141  1495468800  What happened in Manchester? What we know so f...  1.298024
142  1495555200  Ariana Grande suspends European concert tour a...  1.293447
143  1495641600  Amber Rudd denies cuts to police were factor i...  1.295343
144  1495728000  SFO delays decision again on charging Barclays...  1.279254
145  1495814400  Labor has no choice. It should acccept Gonski ...  1.280321
146  1495900800  Armed police arrest man during fresh raids in ...  1.280234
147  1495987200  Did Manchester bomber work alone? Unlikely, sa...  1.284527
148  1496073600  Police believe Manchester bomber Salman Abedi ...  1.285948
149  1496160000  How quickly talk changes: from ever-booming ho...  1.289987
150  1496246400  New images of Manchester bomber Salman Abedi r...  1.289324

[151 rows x 3 columns]

In [8]:
data.to_csv('newstitle_gbp(uk-news,world,business,technology,money_2017-5-31).csv', index=False)