In [2]:
import pandas as pd
import numpy as np
import MySQLdb
import re
from datetime import datetime
from matplotlib import pyplot as plt
conn = MySQLdb.connect(host='54.65.19.253', port=3306, user='news', passwd='newsnews', db='news')

In [3]:
news_title = pd.read_csv('news_title.csv')
news_title.head()

,name,class,date,timestamp
0,cia exposed by frontline role along afghanista...,world,2010/jan/01,1262275200
1,iraq threatens action after blackwater case co...,world,2010/jan/01,1262275200
2,racial or religious groups could be picked out...,world,2010/jan/01,1262275200
3,us general british hostage held in iran,world,2010/jan/01,1262275200
4,pakistan suicide bomber kills dozens at volley...,world,2010/jan/01,1262275200

In [4]:
def getdata(news_class):
    conn = MySQLdb.connect(host='54.65.19.253', port=3306, user='news', passwd='newsnews', db='news')
    news = pd.read_csv('news_title.csv')
    news = news.loc[news['class'].isin(news_class)]
    news = news.drop(['date', 'class'], axis=1)
    news = news.groupby('timestamp', as_index=False).agg(lambda name: ' '.join(name))
    gbp = pd.read_sql('SELECT gbp.timestamp, gbp \
                FROM gbp \
                WHERE gbp.timestamp >= 1262275200;', conn)
    news = pd.merge(news, gbp, on='timestamp', how='inner')
    return news

In [7]:
news_class = ['world']#['lifestyle','travel']
data = getdata(news_class)

In [8]:
data

       timestamp                                               name       gbp
0     1262275200  cia exposed by frontline role along afghanista...  1.616810
1     1262361600  somali charged with murder attempt on muhammad...  1.620700
2     1262448000  ethiopia firm recycling tyres into shoes does ...  1.616800
3     1262534400  militants behind embassy threats killed  yemen...  1.610591
4     1262620800  more body searches  sniffer dogs and luggage i...  1.600088
5     1262707200  western diplomats to pursue tough un sanctions...  1.601267
6     1262793600  british troops tried to rescue hostages at ira...  1.591234
7     1262880000  spain calls for europe wide protection for bat...  1.599166
8     1262966400  cia bomber  martyrdom  video urges more us att...  1.602100
9     1263052800  iran parliament exposes abuse of opposition pr...  1.602100
10    1263139200  drug companies face european inquiry over swin...  1.614429
11    1263225600  haiti feels force of major earthquake allegati...  1.618031
12    1263312000  haiti must call on survival spirit grinding po...  1.628565
13    1263398400  accounts invaded  computers infected human rig...  1.632267
14    1263484800  security and health are haiti priorities un hu...  1.623972
15    1263571200  frantic race against time to get clean water t...  1.626550
16    1263657600  haiti earthquake  social and economic fabric m...  1.626200
17    1263744000  avatar even in    reportedly too hot property ...  1.632554
18    1263830400  nanga parbat film restarts row over messner br...  1.636785
19    1263916800  port au prince resilience shown as survivors s...  1.628541
20    1264003200  arms maker to remove  biblical  gunsight messa...  1.620529
21    1264089600  haiti aid effort  could have saved more  unide...  1.611608
22    1264176000  miracle survivor found as haiti rescue teams o...  1.611300
23    1264262400  haiti earthquake death toll rises to   and cou...  1.611300
24    1264348800  baghdad suicide bombers and gunmen kill dozens...  1.623517
25    1264435200  karzai told he cannot duck tackling corruption...  1.616074
26    1264521600  nicolas sarkozy awaits verdict on clearstream ...  1.620266
27    1264608000  french court acquits dominique de villepin of ...  1.614237
28    1264694400  the beaver goes under ex bae middleman charged...  1.600979
29    1264780800  unknown soldier buried in france   years after...  1.599800
...          ...                                                ...       ...
2520  1480608000  steep rise in police requests for opal data to...  1.268148
2521  1480694400  revealed  the new face of neil prakash  austra...  1.272760
2522  1480780800  climate change likely cause of freak avalanche...  1.272780
2523  1480867200  mh  search  families of passengers to comb mad...  1.270852
2524  1480953600  south korean president park geun hye defies ca...  1.270575
2525  1481040000  sara connor looked  messy  and  pale bali murd...  1.260501
2526  1481126400  vietnam dredges reef disputed with china chech...  1.257591
2527  1481212800  nana akufo addo wins poll to become ghana pres...  1.258145
2528  1481299200  le canard enchai ne  celebrates   years of mis...  1.257300
2529  1481385600  kyrgyzstan votes to increase government powers...  1.257100
2530  1481472000  britain pandering to saudi confrontation dicke...  1.267493
2531  1481558400  mexican drug leader mother kidnapped by vigila...  1.268368
2532  1481644800  widow of bali policeman rejects compensation o...  1.271379
2533  1481731200  the hardest winter in living memory uk and us ...  1.238533
2534  1481817600  aleppo  cosmopolitan city built on thousands o...  1.247686
2535  1481904000  muslim cleric banned in pakistan is preaching ...  1.248950
2536  1481990400  israeli occupants of illegal west bank outpost...  1.249000
2537  1482076800  indonesia military transport plane crashes in ...  1.241528
2538  1482163200  eddie obeid denied bail days after he was sent...  1.235645
2539  1482249600  china restricts sharing of  unofficial  videos...  1.235043
2540  1482336000  the earth is flat  trump is democrat   and oth...  1.229937
2541  1482422400  us abstention allows un to demand end to israe...  1.225293
2542  1482508800  pope francis  christmas has been  taken hostag...  1.228500
2543  1482595200  egypt arrests al jazeera journalist over  prov...  1.227800
2544  1482681600  fake news story prompts pakistan to issue nucl...  1.228694
2545  1482768000  shinzo abe visits pearl harbor in what barack ...  1.226001
2546  1482854400  on the hunt for illegal miners as new gold rus...  1.222100
2547  1482940800  want to know what it like to be woman in boy c...  1.223908
2548  1483027200  greek envoy wife and two men detained in rio d...  1.233779
2549  1483113600  drc parties reach deal denying third term for ...  1.233210

[2550 rows x 3 columns]